version: '3'

services:
  db:
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'booking-app-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted so the data won't lost on recreating of the continer
    volumes:
      - booking-app-db:/var/lib/mysql
# Names our volume
volumes:
  booking-app-db:
